# Generated by Django 5.1.4 on 2025-02-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='oedered',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='oedered_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='oders',
            new_name='orders',
        ),
    ]
